FROM python:3.12-slim

WORKDIR /app

COPY shared /tmp/shared
RUN pip install --no-cache-dir /tmp/shared

COPY order-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY order-service/app ./app

EXPOSE 8003

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]
