cluster:
  name: openhands-k3s

destinations:
  grafana-cloud-metrics:
    type: prometheus
    url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
    auth:
      type: basic
      username: "2578475"
      password: glc_eyJvIjoiMTQ5MTQ4NiIsIm4iOiJzdGFjay0xMzI3MTIwLWludGVncmF0aW9uLWRlZmF1bHQtZGVmYXVsdCIsImsiOiJ6ZzM0NlUzZkI2UldWcWE5NDBiUTRHUzEiLCJtIjp7InIiOiJwcm9kLXVzLXdlc3QtMCJ9fQ==

  grafana-cloud-logs:
    type: loki
    url: https://logs-prod-021.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "1284914"
      password: glc_eyJvIjoiMTQ5MTQ4NiIsIm4iOiJzdGFjay0xMzI3MTIwLWludGVncmF0aW9uLWRlZmF1bHQtZGVmYXVsdCIsImsiOiJ6ZzM0NlUzZkI2UldWcWE5NDBiUTRHUzEiLCJtIjp7InIiOiJwcm9kLXVzLXdlc3QtMCJ9fQ==

clusterMetrics:
  enabled: true
  collector: alloy-metrics

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: false
  energyMetrics:
    enabled: false

costMetrics:
  enabled: true
  collector: alloy-metrics

clusterEvents:
  enabled: true
  collector: alloy-singleton

podLogsViaLoki:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-singleton:
    presets:
      - singleton
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset

collectorCommon:
  alloy:
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-014.grafana.net
      auth:
        type: basic
        username: "1327120"
        password: glc_eyJvIjoiMTQ5MTQ4NiIsIm4iOiJzdGFjay0xMzI3MTIwLWludGVncmF0aW9uLWRlZmF1bHQtZGVmYXVsdCIsImsiOiJ6ZzM0NlUzZkI2UldWcWE5NDBiUTRHUzEiLCJtIjp7InIiOiJwcm9kLXVzLXdlc3QtMCJ9fQ==

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: false
  opencost:
    deploy: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: openhands-k3s
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom
  kepler:
    deploy: false
