apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-disk-janitor.fullname" . }}
  namespace: {{ include "node-disk-janitor.namespace" . }}
  labels:
    {{- include "node-disk-janitor.labels" . | nindent 4 }}
