{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.store.create (eq .Values.externalSecrets.store.kind "ClusterSecretStore") }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.store.name }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.store.region | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.store.authSecret.name | quote }}
            key: {{ .Values.externalSecrets.store.authSecret.accessKeyIdKey | quote }}
            namespace: {{ .Values.externalSecrets.store.authSecret.namespace | quote }}
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.store.authSecret.name | quote }}
            key: {{ .Values.externalSecrets.store.authSecret.secretAccessKeyKey | quote }}
            namespace: {{ .Values.externalSecrets.store.authSecret.namespace | quote }}
{{- end }}

{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.store.create (eq .Values.externalSecrets.store.kind "SecretStore") }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.store.name }}
  namespace: {{ include "strategy-tester.namespace" . }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.store.region | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.store.authSecret.name | quote }}
            key: {{ .Values.externalSecrets.store.authSecret.accessKeyIdKey | quote }}
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.store.authSecret.name | quote }}
            key: {{ .Values.externalSecrets.store.authSecret.secretAccessKeyKey | quote }}
{{- end }}
