{{- if .Values.optionIngestor.cronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "strategy-tester.fullname" . }}-option-ingestor
  namespace: {{ include "strategy-tester.namespace" . }}
  labels:
    app: option-ingestor
    {{- include "strategy-tester.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.optionIngestor.cronJob.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.optionIngestor.cronJob.backoffLimit }}
      template:
        metadata:
          labels:
            app: option-ingestor
            {{- include "strategy-tester.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.optionIngestor.cronJob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: option-ingestor
              image: "{{ .Values.optionIngestor.image.repository }}:{{ .Values.optionIngestor.image.tag }}"
              imagePullPolicy: {{ .Values.optionIngestor.image.pullPolicy }}
              {{- with .Values.optionIngestor.env }}
              env:
                {{- range $key, $value := . }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              {{- end }}
              {{- if .Values.externalSecrets.enabled }}
              envFrom:
                - secretRef:
                    name: {{ .Values.externalSecrets.targetSecretName }}
              {{- end }}
              resources:
                {{- toYaml .Values.optionIngestor.resources | nindent 16 }}
{{- end }}
