apiVersion: v1
kind: Service
metadata:
  name: {{ include "strategy-tester.fullname" . }}-snapshot-ingestor
  namespace: {{ include "strategy-tester.namespace" . }}
  labels:
    app: snapshot-ingestor
    {{- include "strategy-tester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.snapshotIngestor.service.type }}
  ports:
    - port: {{ .Values.snapshotIngestor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: snapshot-ingestor
    {{- include "strategy-tester.selectorLabels" . | nindent 4 }}
