apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ required "githubToken is required" .Values.githubToken | quote }}
  AGENT_AUTH_TOKEN: {{ required "agentAuthToken is required" .Values.agentAuthToken | quote }}
