{{- if and .Values.postgres.enabled (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: flashsales-postgres-auth
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@flashsales-postgres:%v/%s" .Values.postgres.auth.username .Values.postgres.auth.password .Values.postgres.service.port .Values.postgres.auth.database | quote }}
{{- end }}
