apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashsales-product-service
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
spec:
  replicas: {{ .Values.productService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: product-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: product-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: product-service
          image: "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"
          imagePullPolicy: {{ .Values.productService.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.productService.env.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.productService.env.dbPort | quote }}
            - name: DB_NAME
              value: {{ .Values.productService.env.dbName | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: flashsales-postgres-auth
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flashsales-postgres-auth
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: {{ .Values.productService.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.productService.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.productService.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
