{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flashsales-rabbitmq
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  serviceName: flashsales-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: flashsales-rabbitmq-auth
          ports:
            - containerPort: {{ .Values.rabbitmq.service.amqpPort }}
              name: amqp
            - containerPort: {{ .Values.rabbitmq.service.managementPort }}
              name: management
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 20
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.rabbitmq.storage.className }}
        storageClassName: {{ .Values.rabbitmq.storage.className | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.storage.size }}
{{- end }}
