{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flashsales-rabbitmq-auth
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.rabbitmq.auth.vhost | quote }}
{{- end }}
