{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: flashsales-rabbitmq
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  selector:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
      protocol: TCP
      name: management
{{- end }}
