apiVersion: v1
kind: ConfigMap
metadata:
  name: flashsales-user-service-config
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
data:
  DB_HOST: {{ .Values.userService.env.dbHost | quote }}
  DB_PORT: {{ .Values.userService.env.dbPort | quote }}
  DB_NAME: {{ .Values.userService.env.dbName | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flashsales-product-service-config
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
data:
  DB_HOST: {{ .Values.productService.env.dbHost | quote }}
  DB_PORT: {{ .Values.productService.env.dbPort | quote }}
  DB_NAME: {{ .Values.productService.env.dbName | quote }}
  INVENTORY_LOCK_MODE: {{ .Values.productService.env.inventoryLockMode | default "optimistic" | quote }}
  OPTIMISTIC_RETRY_LIMIT: {{ .Values.productService.env.optimisticRetryLimit | default "5" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flashsales-order-service-config
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
data:
  USER_SERVICE_URL: {{ .Values.orderService.env.userServiceUrl | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.orderService.env.productServiceUrl | quote }}
  DEPENDENCY_TIMEOUT_SECONDS: {{ .Values.orderService.env.dependencyTimeoutSeconds | quote }}
  DB_HOST: {{ ternary "flashsales-db-proxy" .Values.orderService.env.dbHost .Values.dbProxy.enabled | quote }}
  DB_PORT: {{ ternary (.Values.dbProxy.service.dataPort | toString) .Values.orderService.env.dbPort .Values.dbProxy.enabled | quote }}
  DB_NAME: {{ .Values.orderService.env.dbName | quote }}
  REDIS_URL: {{ .Values.orderService.env.redisUrl | quote }}
  RABBITMQ_URL: {{ .Values.orderService.env.rabbitmqUrl | quote }}
  INVENTORY_LOCK_MODE: {{ .Values.orderService.env.inventoryLockMode | default "optimistic" | quote }}
  OPTIMISTIC_RETRY_LIMIT: {{ .Values.orderService.env.optimisticRetryLimit | default "5" | quote }}
