apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashsales-user-service
  namespace: {{ include "flashsales.namespace" . }}
  labels:
    {{- include "flashsales.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  {{- if not .Values.userService.autoscaling.enabled }}
  replicas: {{ .Values.userService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: user-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: user-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: flashsales-user-service-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: flashsales-postgres-auth
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flashsales-postgres-auth
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flashsales-postgres-auth
                  key: DATABASE_URL
                  optional: true
          ports:
            - containerPort: {{ .Values.userService.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.userService.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.userService.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- with .Values.userService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
