{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.store.create }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.store.name }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.store.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.store.authSecret.name }}
            key: {{ .Values.externalSecrets.store.authSecret.accessKeyIdKey }}
            namespace: {{ .Values.externalSecrets.store.authSecret.namespace }}
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.store.authSecret.name }}
            key: {{ .Values.externalSecrets.store.authSecret.secretAccessKeyKey }}
            namespace: {{ .Values.externalSecrets.store.authSecret.namespace }}
{{- end }}
