apiVersion: v2
name: strategy-tester
description: Strategy Tester microservices chart for k3s
type: application
version: 0.1.1
appVersion: "0.1.0"

dependencies:
  - name: ssm-common
    version: 0.1.0
    repository: file://../common/ssm-common
