namespaceOverride: ""

imagePullSecrets:
  - name: ghcr-pull-secret

observability:
  tracing:
    otlpProtocol: "http/protobuf"
    otlpHttpEndpoint: "https://otlp-gateway-prod-us-west-0.grafana.net/otlp/v1/traces"
    otlpHeaders: "Authorization=Basic MTMyNzEyMDpnbGNfZXlKdklqb2lNVFE1TVRRNE5pSXNJbTRpT2lKemRHRmpheTB4TXpJM01USXdMVzkwYkhBdGQzSnBkR1V0YUc5dFpXeGhZaUlzSW1zaU9pSnZkRWd6T1ZoMk9URmtOMGhKU0hjM016RmlObkUzUm1raUxDSnRJanA3SW5JaU9pSndjbTlrTFhWekxYZGxjM1F0TUNKOWZRPT0="
    externalSecretEnabled: false
    externalSecretKey: "OTEL_EXPORTER_OTLP_HEADERS"
    existingSecretName: ""
    existingSecretKey: "OTEL_EXPORTER_OTLP_HEADERS"

externalSecrets:
  enabled: true
  refreshInterval: 1h
  targetSecretName: strategy-tester-apis
  parameterPrefix: /strategy-tester/prod
  store:
    kind: ClusterSecretStore
    name: strategy-tester-aws-ssm
    create: true
    region: us-west-1
    authSecret:
      name: aws-ssm-credentials
      namespace: external-secrets
      accessKeyIdKey: access-key-id
      secretAccessKeyKey: secret-access-key

optionIngestor:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  image:
    repository: ghcr.io/jingyi-zhao-01/strategy-tester-option-ingestor
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "300m"
      memory: "384Mi"
    limits:
      cpu: "750m"
      memory: "768Mi"
  service:
    type: ClusterIP
    port: 8001
  env:
    LOG_LEVEL: INFO
    INGEST_CONCURRENCY_LIMIT: "20"
    INGEST_DB_CONCURRENCY_LIMIT: "20"
    INGEST_DB_WRITE_BATCH_SIZE: "25"
    INGEST_OPTION_BATCH_SIZE: "500"
  cronJob:
    enabled: true
    schedule: "0 22 * * 0-5"
    timeZone: "America/New_York"
    parallelism: 1
    completions: 1
    restartPolicy: OnFailure
    backoffLimit: 1

snapshotIngestor:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  image:
    repository: ghcr.io/jingyi-zhao-01/strategy-tester-snapshot-ingestor
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "300m"
      memory: "384Mi"
    limits:
      cpu: "750m"
      memory: "768Mi"
  service:
    type: ClusterIP
    port: 8002
  env:
    LOG_LEVEL: INFO
    INGEST_CONCURRENCY_LIMIT: "20"
    INGEST_DB_CONCURRENCY_LIMIT: "20"
    INGEST_OPTION_BATCH_SIZE: "500"
    SNAPSHOT_FETCH_CONCURRENCY: "50"
    SNAPSHOT_FETCH_BATCH_SIZE: "25"
    SNAPSHOT_FETCH_CONNECT_TIMEOUT: "10.0"
    SNAPSHOT_FETCH_READ_TIMEOUT: "10.0"
    SNAPSHOT_HTTP_MAX_CONNECTIONS: "50"
    SNAPSHOT_HTTP_MAX_KEEPALIVE_CONNECTIONS: "20"
  cronJob:
    enabled: true
    schedule: "0 23 * * 0-5"
    timeZone: "America/New_York"
    parallelism: 1
    completions: 1
    restartPolicy: OnFailure
    backoffLimit: 1
