apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: datadog-aws-ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm-credentials
            key: access-key-id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-ssm-credentials
            key: secret-access-key
            namespace: external-secrets
