apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: openhands-k3s
    site: us5.datadoghq.com
    tags:
      - env:prod
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    admissionController:
      enabled: true
      mutateUnlabelled: false
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    otlp:
      receiver:
        protocols:
          http:
            enabled: true
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: default-target
            namespaceSelector:
              matchNames:
                - flashsales
            ddTraceVersions:
              python: "4"
    logCollection:
      enabled: true
      containerCollectAll: true
