apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: datadog-aws-ssm
  target:
    name: datadog-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: /datadog/api_key
